// Package logloom provides an slog.Handler that enriches log records
// with LogLoom code-provenance metadata from the build-time AST graph.
//
// # Quick Start
//
// In your application's logger initialization, wrap your base handler:
//
//	import "github.com/Fremen-Labs/logloom-go/logloom"
//
//	baseHandler := slog.NewJSONHandler(os.Stdout, nil)
//	logger := slog.New(logloom.NewHandler(baseHandler))
//
// The handler is zero-overhead when no graph is loaded: logs pass through
// unchanged.  When logloom-graph.json is present (generated by logloom build),
// each log message is matched against the graph's node index and enriched with
// the originating source file, function, module, and semantic tags.
//
// # Graph Discovery
//
// The handler discovers logloom-graph.json in this order:
//
//  1. LOGLOOM_GRAPH_PATH environment variable (explicit path)
//  2. Walk up from CWD (max 10 levels)
//
// # Enrichment Fields
//
// When a match is found, the handler injects these slog attributes:
//
//   - logloom_node_id    — stable hash identifying the log call site
//   - logloom_module     — source module (e.g. "src/gateway/providers")
//   - logloom_function   — function name (e.g. "ProviderRouter.Route")
//   - logloom_tags       — semantic tags (e.g. ["auth", "error", "http"])
package logloom

import (
	"context"
	"encoding/json"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
)

// ─── Graph model ────────────────────────────────────────────────────────────

// Graph represents the parsed logloom-graph.json.
type Graph struct {
	Project   string           `json:"project"`
	Nodes     map[string]*Node `json:"nodes"`
	CommitSHA string           `json:"commit_sha"`
}

// Node represents a single log-call site discovered by the LogLoom AST scanner.
type Node struct {
	File            string   `json:"file"`
	Module          string   `json:"module"`
	Function        string   `json:"function"`
	MessageTemplate string   `json:"message_template"`
	SemanticTags    []string `json:"semantic_tags"`
	Line            int      `json:"line"`
}

// ─── Singleton graph loader ─────────────────────────────────────────────────

var (
	globalGraph *Graph
	// exactIndex maps message_template → (node_id, *Node) for O(1) exact match.
	exactIndex map[string]indexEntry
	initOnce   sync.Once
	// graphLoaded can be checked after LoadGraph to confirm discovery succeeded.
	graphLoaded bool
)

type indexEntry struct {
	id       string
	node     *Node
	collides bool // true when multiple nodes share the same message_template
}

const graphFileName = "logloom-graph.json"

// LoadGraph attempts to discover and load logloom-graph.json.
// Discovery order:
//  1. LOGLOOM_GRAPH_PATH environment variable
//  2. Walk up from CWD (max 10 levels)
//
// Safe to call multiple times; only the first call has effect.
func LoadGraph() {
	initOnce.Do(func() {
		// Strategy 1: explicit env var
		if envPath := os.Getenv("LOGLOOM_GRAPH_PATH"); envPath != "" {
			if tryLoad(envPath) {
				return
			}
		}
		// Strategy 2: walk up from CWD
		dir, err := os.Getwd()
		if err != nil {
			return
		}
		for i := 0; i < 10; i++ {
			if tryLoad(filepath.Join(dir, graphFileName)) {
				return
			}
			parent := filepath.Dir(dir)
			if parent == dir {
				break
			}
			dir = parent
		}
	})
}

func tryLoad(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	var graph Graph
	if err := json.Unmarshal(data, &graph); err != nil {
		return false
	}
	globalGraph = &graph
	graphLoaded = true
	buildIndex()
	return true
}

// buildIndex creates the O(1) exact-match lookup table from the graph.
// Templates that appear in multiple nodes are marked as collisions so
// the resolver falls through to Tier-2 (function-scoped) matching.
func buildIndex() {
	exactIndex = make(map[string]indexEntry, len(globalGraph.Nodes))
	for id, node := range globalGraph.Nodes {
		if existing, exists := exactIndex[node.MessageTemplate]; exists {
			// Mark the existing entry as a collision — Tier-1 cannot
			// disambiguate, so resolve() will fall through to Tier-2.
			existing.collides = true
			exactIndex[node.MessageTemplate] = existing
		} else {
			exactIndex[node.MessageTemplate] = indexEntry{id: id, node: node}
		}
	}
}

// GraphLoaded returns true if the graph was discovered and loaded successfully.
func GraphLoaded() bool {
	return graphLoaded
}

// NodeCount returns the number of nodes in the loaded graph, or 0 if unloaded.
func NodeCount() int {
	if globalGraph == nil {
		return 0
	}
	return len(globalGraph.Nodes)
}

// ─── slog.Handler implementation ────────────────────────────────────────────

// Handler is an slog.Handler that enriches log records with LogLoom metadata.
// It wraps an inner handler; when no graph is loaded, it passes records
// through unchanged (zero overhead).
type Handler struct {
	inner slog.Handler
}

// NewHandler creates a LogLoom enriching handler wrapping the given inner handler.
// Automatically discovers and loads logloom-graph.json on first call.
func NewHandler(inner slog.Handler) *Handler {
	LoadGraph()
	return &Handler{inner: inner}
}

// Enabled delegates to the inner handler.
func (h *Handler) Enabled(ctx context.Context, level slog.Level) bool {
	return h.inner.Enabled(ctx, level)
}

// Handle enriches the record with LogLoom metadata and passes it to the inner handler.
func (h *Handler) Handle(ctx context.Context, r slog.Record) error {
	if globalGraph == nil {
		return h.inner.Handle(ctx, r)
	}

	id, node := resolve(r)
	if node == nil {
		return h.inner.Handle(ctx, r)
	}

	// Clone the record and inject LogLoom attributes
	enriched := slog.NewRecord(r.Time, r.Level, r.Message, r.PC)
	r.Attrs(func(a slog.Attr) bool {
		enriched.AddAttrs(a)
		return true
	})
	enriched.AddAttrs(
		slog.String("logloom_node_id", id),
		slog.String("logloom_module", node.Module),
		slog.String("logloom_function", node.Function),
		slog.String("logloom_file", node.File),
		slog.Int("logloom_line", node.Line),
	)
	if len(node.SemanticTags) > 0 {
		enriched.AddAttrs(slog.Any("logloom_tags", node.SemanticTags))
	}
	return h.inner.Handle(ctx, enriched)
}

// WithAttrs preserves the handler chain.
func (h *Handler) WithAttrs(attrs []slog.Attr) slog.Handler {
	return &Handler{inner: h.inner.WithAttrs(attrs)}
}

// WithGroup preserves the handler chain.
func (h *Handler) WithGroup(name string) slog.Handler {
	return &Handler{inner: h.inner.WithGroup(name)}
}

// ─── Resolution strategy ────────────────────────────────────────────────────

// resolve performs a multi-tier match from the log record to a graph node.
//
// Tier 1: O(1) exact match on message_template
// Tier 2: Function-scoped search using the runtime caller frame
func resolve(r slog.Record) (string, *Node) {
	// Tier 1: O(1) exact match on message text.
	// Only trust the match if the template is unique (no collision).
	if entry, ok := exactIndex[r.Message]; ok && !entry.collides {
		return entry.id, entry.node
	}

	// Tier 2: narrow by caller function (from program counter) and
	// scan for prefix matches — handles formatted messages like
	// fmt.Sprintf("connecting to %s", host)
	if r.PC == 0 {
		return "", nil
	}
	frames := runtime.CallersFrames([]uintptr{r.PC})
	frame, _ := frames.Next()
	shortFunc := normalizeGoFunc(frame.Function)

	for id, node := range globalGraph.Nodes {
		if node.Function == shortFunc && strings.HasPrefix(r.Message, node.MessageTemplate) {
			return id, node
		}
	}

	return "", nil
}

// normalizeGoFunc strips Go module paths and pointer receiver wrappers to
// produce the bare function name that matches the LogLoom graph.
//
// Examples:
//
//	"github.com/Fremen-Labs/flume/src/gateway.(*Server).Start" → "Server.Start"
//	"github.com/Fremen-Labs/flume/src/gateway.InitLogger"      → "InitLogger"
func normalizeGoFunc(fullName string) string {
	// Strip module path: take everything after the last "/"
	short := fullName
	if idx := strings.LastIndex(fullName, "/"); idx >= 0 {
		short = fullName[idx+1:]
	}
	// Strip package prefix: "gateway.(*Server).Start" → "(*Server).Start"
	if idx := strings.Index(short, "."); idx >= 0 {
		short = short[idx+1:]
	}
	// Strip pointer receiver wrapper: "(*Server).Start" → "Server.Start"
	short = strings.TrimPrefix(short, "(*")
	short = strings.Replace(short, ").", ".", 1)
	return short
}
